[project]
name = "discordbot"
version = "0.1.0"
description = "Evil and Intimidating Horse bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.14.3",
    "cachetools>=7.2.0",
    "discord-py>=2.7.1",
    "fromsoft-generator>=1.0.1",
    "geonamescache>=3.0.2",
    "tzdata>=2026.4",
]

[project.scripts]
discordbot = "discordbot:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
